/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab8p2_bladylagos;

import Clases.GestionVehiculos;
import Clases.vehiculos;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gerardo Lagos
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
                setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        crearvehiculo = new javax.swing.JDialog();
        cbcarroceria1 = new javax.swing.JComboBox<>();
        cbhibridacion1 = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        cantpasajeros1 = new javax.swing.JTextField();
        numpuertas1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        ensamblaje1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        vin1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        precio1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cnombre = new javax.swing.JTextField();
        cbmotor1 = new javax.swing.JComboBox<>();
        cbmarca1 = new javax.swing.JComboBox<>();
        motor1 = new javax.swing.JTextField();
        jDialog2 = new javax.swing.JDialog();
        cb_1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jp1 = new javax.swing.JPopupMenu();
        editar = new javax.swing.JMenuItem();
        delete = new javax.swing.JMenuItem();
        modificacion = new javax.swing.JDialog();
        jLabel14 = new javax.swing.JLabel();
        m = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        c = new javax.swing.JRadioButton();
        jLabel23 = new javax.swing.JLabel();
        c1 = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        n1 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        n = new javax.swing.JRadioButton();
        m11 = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();
        marca1 = new javax.swing.JTextField();
        m1 = new javax.swing.JTextField();
        mostrarCategoria = new javax.swing.JDialog();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        mostrarGeneralista = new javax.swing.JDialog();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        cb = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton11 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        cbcarroceria1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "sedan", "familiar", "hatchback", "fastback", "SUV" }));

        cbhibridacion1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ninguna", "microhibrido", "hibrido convencional", "electrico" }));

        jLabel19.setText("cant pasajeros");

        jLabel18.setText("marca");

        jLabel20.setText("Ensamblaje");

        jLabel21.setText("Carroceria");

        jLabel26.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel26.setText("Vehiculos");

        jLabel22.setText("hibridacion");

        jLabel25.setText("num puertas");

        jLabel17.setText("precio");

        jLabel15.setText("Vin");

        jLabel16.setText("motor");

        jButton2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton2.setText("Guardar Vehiculo");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Nombre Base Datos");

        cbmotor1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "combustible", "electrico" }));

        cbmarca1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SEAT", "Škoda", "Audi", "Volkswagen", "Bentley", "Porsche", "Lamborghini", "Bugatti" }));

        javax.swing.GroupLayout crearvehiculoLayout = new javax.swing.GroupLayout(crearvehiculo.getContentPane());
        crearvehiculo.getContentPane().setLayout(crearvehiculoLayout);
        crearvehiculoLayout.setHorizontalGroup(
            crearvehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, crearvehiculoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(350, 350, 350))
            .addGroup(crearvehiculoLayout.createSequentialGroup()
                .addGroup(crearvehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(crearvehiculoLayout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addGroup(crearvehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(crearvehiculoLayout.createSequentialGroup()
                                .addGroup(crearvehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel15))
                                .addGroup(crearvehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, crearvehiculoLayout.createSequentialGroup()
                                        .addGap(60, 60, 60)
                                        .addComponent(cbcarroceria1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(crearvehiculoLayout.createSequentialGroup()
                                        .addGap(59, 59, 59)
                                        .addGroup(crearvehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(vin1, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                                            .addComponent(cbmarca1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, crearvehiculoLayout.createSequentialGroup()
                                .addGroup(crearvehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(crearvehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(numpuertas1, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                                    .addComponent(cbmotor1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(111, 111, 111)
                        .addGroup(crearvehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel20)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addGap(56, 56, 56)
                        .addGroup(crearvehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbhibridacion1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cantpasajeros1)
                            .addComponent(ensamblaje1)
                            .addComponent(precio1)))
                    .addGroup(crearvehiculoLayout.createSequentialGroup()
                        .addGap(366, 366, 366)
                        .addComponent(jLabel26))
                    .addGroup(crearvehiculoLayout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addComponent(jLabel1)
                        .addGap(6, 6, 6)
                        .addComponent(cnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        crearvehiculoLayout.setVerticalGroup(
            crearvehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crearvehiculoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(crearvehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(crearvehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(crearvehiculoLayout.createSequentialGroup()
                        .addGroup(crearvehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(vin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(crearvehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(cbmarca1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(crearvehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(cbcarroceria1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(crearvehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(numpuertas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(crearvehiculoLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel22)
                        .addGap(17, 17, 17)
                        .addComponent(jLabel19))
                    .addGroup(crearvehiculoLayout.createSequentialGroup()
                        .addGroup(crearvehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(precio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbhibridacion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(cantpasajeros1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(crearvehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ensamblaje1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(crearvehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(cbmotor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(216, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog2Layout.createSequentialGroup()
                .addContainerGap(397, Short.MAX_VALUE)
                .addComponent(cb_1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(354, 354, 354))
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog2Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(cb_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(480, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        editar.setText("Modificar");
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });
        jp1.add(editar);

        delete.setText("Eliminar");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jp1.add(delete);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Que Desea Modificar");

        m.setText("marca");

        jLabel2.setText("Marca:");

        jButton4.setText("Modificar Marca");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        c.setText("carroceria");

        jLabel23.setText("Carroceria");

        c1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "sedan", "familiar", "hatchback", "fastback", "SUV" }));

        jButton5.setText("Modificar Carroceria");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel27.setText("num puertas");

        jButton7.setText("Modificar num puertas");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        n.setText("numpuertas");

        m11.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SEAT", "Škoda", "Audi", "Volkswagen", "Bentley", "Porsche", "Lamborghini", "Bugatti" }));

        javax.swing.GroupLayout modificacionLayout = new javax.swing.GroupLayout(modificacion.getContentPane());
        modificacion.getContentPane().setLayout(modificacionLayout);
        modificacionLayout.setHorizontalGroup(
            modificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificacionLayout.createSequentialGroup()
                .addGroup(modificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(modificacionLayout.createSequentialGroup()
                        .addGap(379, 379, 379)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(modificacionLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(modificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(modificacionLayout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addGap(18, 18, 18)
                                .addComponent(n1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(modificacionLayout.createSequentialGroup()
                                .addGroup(modificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel2))
                                .addGap(34, 34, 34)
                                .addGroup(modificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(m11, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(108, 108, 108)
                        .addGroup(modificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(modificacionLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(m)
                        .addGap(26, 26, 26)
                        .addComponent(c)
                        .addGap(18, 18, 18)
                        .addComponent(n)))
                .addContainerGap(384, Short.MAX_VALUE))
        );
        modificacionLayout.setVerticalGroup(
            modificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificacionLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel14)
                .addGap(50, 50, 50)
                .addGroup(modificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m)
                    .addComponent(c)
                    .addComponent(n))
                .addGap(32, 32, 32)
                .addGroup(modificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButton4)
                    .addComponent(m11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(modificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addGap(21, 21, 21)
                .addGroup(modificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel27)
                    .addGroup(modificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(n1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton7)))
                .addContainerGap(363, Short.MAX_VALUE))
        );

        jButton6.setText("Modificar Carroceria");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton8.setText("Generalista");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Premium");

        jButton10.setText("Deportivo");

        javax.swing.GroupLayout mostrarCategoriaLayout = new javax.swing.GroupLayout(mostrarCategoria.getContentPane());
        mostrarCategoria.getContentPane().setLayout(mostrarCategoriaLayout);
        mostrarCategoriaLayout.setHorizontalGroup(
            mostrarCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mostrarCategoriaLayout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(169, Short.MAX_VALUE))
        );
        mostrarCategoriaLayout.setVerticalGroup(
            mostrarCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mostrarCategoriaLayout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addGroup(mostrarCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(338, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mostrarGeneralistaLayout = new javax.swing.GroupLayout(mostrarGeneralista.getContentPane());
        mostrarGeneralista.getContentPane().setLayout(mostrarGeneralistaLayout);
        mostrarGeneralistaLayout.setHorizontalGroup(
            mostrarGeneralistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 805, Short.MAX_VALUE)
        );
        mostrarGeneralistaLayout.setVerticalGroup(
            mostrarGeneralistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 572, Short.MAX_VALUE)
        );

        jButton3.setText("Mostrar En Categoria");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setText("Crear Vehiculo");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        cb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbItemStateChanged(evt);
            }
        });

        jTable2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vin", "Marca", "Carroceria", "Numero Puertas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jButton11.setText("Generalista");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Mostrar En Categoria");

        jButton12.setText("Premium");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setText("Deportivos");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Click Derecho En La Tabla Para Mostrar El Popup Menu");

        jButton14.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton14.setText("Buscar Vehiculos ");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton15.setText("Guardar Archivo ");
        jButton15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton15MouseClicked(evt);
            }
        });

        jButton16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton16.setText("Cargar Archivo");
        jButton16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton16MouseClicked(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Seleccione con click izquiero a un vehiculo");

        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Para guardar en archivos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(27, 27, 27))
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(235, 235, 235)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(276, 276, 276)
                                .addComponent(cb, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(64, 64, 64))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(271, 271, 271)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)))
                        .addGap(36, 36, 36)
                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(cb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(128, 128, 128))
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton14)
                .addGap(18, 18, 18)
                .addComponent(jButton15)
                .addGap(18, 18, 18)
                .addComponent(jButton16)
                .addGap(32, 32, 32)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        crearvehiculo.setModal(true);
        crearvehiculo.pack();
        crearvehiculo.setLocationRelativeTo(this);
        crearvehiculo.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        String vin2 = vin1.getText();
        String marca2 = "";

        if (cbmarca1.getSelectedIndex() == 0) {
            marca2 = "SEAT";
        }//
        if (cbmarca1.getSelectedIndex() == 1) {
            marca2 = "Škoda";
        }

        if (cbmarca1.getSelectedIndex() == 2) {
            marca2 = "Audi";
        }
        if (cbmarca1.getSelectedIndex() == 3) {
            marca2 = "Volkswagen";
        }
        if (cbmarca1.getSelectedIndex() == 4) {
            marca2 = "Bentley";
        }

        if (cbmarca1.getSelectedIndex() == 5) {
            marca2 = "Porsche";
        }
        if (cbmarca1.getSelectedIndex() == 6) {
            marca2 = "Lamborghini";
        }
        if (cbmarca1.getSelectedIndex() == 7) {
            marca2 = "Bugatti";
        }

///////////////
        String carroceria2 = "";

        if (cbcarroceria1.getSelectedIndex() == 0) {
            carroceria2 = "sedan";
        }
        if (cbcarroceria1.getSelectedIndex() == 1) {
            carroceria2 = "familiar";
        }
        if (cbcarroceria1.getSelectedIndex() == 2) {
            carroceria2 = "hatchback";
        }
        if (cbcarroceria1.getSelectedIndex() == 3) {
            carroceria2 = "fastback";
        }
        if (cbcarroceria1.getSelectedIndex() == 4) {
            carroceria2 = "SUV";
        }

        String numpuertas2 = numpuertas1.getText();

        String motor2 = "";

        if (cbmotor1.getSelectedIndex() == 3) {
            motor2 = "combustible";
        }
        if (cbmotor1.getSelectedIndex() == 4) {
            motor2 = "electrico";
        }

        String precio2 = precio1.getText();

        String hibridacion2 = "";

        if (cbhibridacion1.getSelectedIndex() == 0) {
            hibridacion2 = "ninguna";
        }
        if (cbhibridacion1.getSelectedIndex() == 1) {
            hibridacion2 = "microhíbrido";
        }
        if (cbhibridacion1.getSelectedIndex() == 2) {
            hibridacion2 = "híbrido convencional";
        }
        if (cbhibridacion1.getSelectedIndex() == 3) {
            hibridacion2 = "eléctrico";
        }

        String cantpasajeros2 = cantpasajeros1.getText();

        String ensamblaje2 = ensamblaje1.getText();

        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb.getModel();
        DefaultComboBoxModel modelo2 = (DefaultComboBoxModel) cb_1.getModel();
        vehiculos p = new vehiculos(vin2, marca2, carroceria2, numpuertas2, motor2, precio2, hibridacion2, cantpasajeros2, ensamblaje2);
        if (GestionVehiculos.existelistavehiculos(vin1.getText()) == false) {
            GestionVehiculos.agregarVehiculo(p);
            JOptionPane.showMessageDialog(this, "Vehiculo agregado exitosamente");
            vin1.setText("");
            numpuertas1.setText("");
            precio1.setText("");
            cantpasajeros1.setText("");
            ensamblaje1.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "Ya existe vehiculo con ese Vin");
        }

        cb.setModel(modelo);
        cb_1.setModel(modelo2);
        David c = new David();
        c.getLista().add(p);
        c.setNombre(cnombre.getText());
        modelo.addElement(c);
        modelo2.addElement(c);
        cnombre.setText("");


    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
//mostrarCategoria
        mostrarCategoria.setModal(true);
        mostrarCategoria.pack();
        mostrarCategoria.setLocationRelativeTo(this);
        mostrarCategoria.setVisible(true);

        /*
                jDialog2.setModal(true);
        jDialog2.pack();
        jDialog2.setLocationRelativeTo(this);
        jDialog2.setVisible(true);
         */
    }//GEN-LAST:event_jButton3MouseClicked

    private void cbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbItemStateChanged
        // TODO add your handling code here:
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb.getModel();
        DefaultTableModel modelo2 = (DefaultTableModel) jTable2.getModel();
        if (evt.getStateChange() == 1) {

            David c = (David) modelo.getSelectedItem();

            for (vehiculos p : c.getLista()) {

                Object[] newRow = {
                    p.getVin(),
                    p.getMarca(),
                    p.getCarroceria(),
                    p.getNumpuertas()
//                    p.getMotor()
//                    p.getPrecio(),
//                    p.getHibridacion(),
//                    p.getCantpasajeros(),
//                    p.getEnsamblaje()
                };
                modelo2.addRow(newRow);
            }
        }
    }//GEN-LAST:event_cbItemStateChanged

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        if (evt.isMetaDown()) {
            if (jTable2.getSelectedRow() >= 0) {
                jp1.show(jTable2, evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_jTable2MouseClicked

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
        // TODO add your handling code here:

        modificacion.setModal(true);
        modificacion.pack();
        modificacion.setLocationRelativeTo(this);
        modificacion.setVisible(true);

    }//GEN-LAST:event_editarActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        try {
            if (jTable2.getSelectedRow() >= 0) {
                DefaultTableModel modelo = (DefaultTableModel) jTable2.getModel();
                modelo.removeRow(jTable2.getSelectedRow());
                jTable2.setModel(modelo);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrio un ERROR");
        }
//        DefaultTableModel modelo = (DefaultTableModel) jTable2.getModel();
//
//        int index = jTable2.getSelectedRow();
//
//        vehiculos c = new vehiculos((String) modelo.getValueAt(index, 0),
//                (String) modelo.getValueAt(index, 1),
//                (String) modelo.getValueAt(index, 2),
//                (String) modelo.getValueAt(index, 3),
//                (String) modelo.getValueAt(index, 4),
//                (String) modelo.getValueAt(index, 5),
//                (String) modelo.getValueAt(index, 6),
//                (String) modelo.getValueAt(index, 7),
//                (String) modelo.getValueAt(index, 8));
//
//        ((David) cb.getSelectedItem()).getLista().remove(index);
//        modelo.removeRow(index);
//
//        Creadas.add(c);
//
//        jTable2.setModel(modelo);
//
//        JOptionPane.showMessageDialog(this, "Eliminado");
//        try {
//            ((David) cb.getSelectedItem()).escribirArchivo();
//        } catch (Exception e) {
//        }
    }//GEN-LAST:event_deleteActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        DefaultTableModel modelt = (DefaultTableModel) jTable2.getModel();
        DefaultComboBoxModel modelc = (DefaultComboBoxModel) cb.getModel();
        if (jTable2.getSelectedRow() >= 0) {
            int indice = jTable2.getSelectedRow();
            String marca2 = "";

            if (m11.getSelectedIndex() == 0) {
                marca2 = "SEAT";
            }
            if (m11.getSelectedIndex() == 1) {
                marca2 = "Škoda";
            }

            if (m11.getSelectedIndex() == 2) {
                marca2 = "Audi";
            }
            if (m11.getSelectedIndex() == 3) {
                marca2 = "Volkswagen";
            }
            if (m11.getSelectedIndex() == 4) {
                marca2 = "Bentley";
            }

            if (m11.getSelectedIndex() == 5) {
                marca2 = "Porsche";
            }
            if (m11.getSelectedIndex() == 6) {
                marca2 = "Lamborghini";
            }
            if (m11.getSelectedIndex() == 7) {
                marca2 = "Bugatti";
            }
            modelt.setValueAt(marca2, indice, 1);
            jTable2.setModel(modelt);
            ((David) cb.getSelectedItem()).getLista().get(indice).setMarca(marca2);
            try {
                ((David) cb.getSelectedItem()).escribirArchivo();
            } catch (IOException ex) {

            }
            JOptionPane.showMessageDialog(this, "Cambiado");
        }
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelt = (DefaultTableModel) jTable2.getModel();
        DefaultComboBoxModel modelc = (DefaultComboBoxModel) cb.getModel();
        if (jTable2.getSelectedRow() >= 0) {
            int indice = jTable2.getSelectedRow();

            String carroceria2 = "";

            if (c1.getSelectedIndex() == 0) {
                carroceria2 = "sedan";
            }
            if (c1.getSelectedIndex() == 1) {
                carroceria2 = "familiar";
            }
            if (c1.getSelectedIndex() == 2) {
                carroceria2 = "hatchback";
            }
            if (c1.getSelectedIndex() == 3) {
                carroceria2 = "fastback";
            }
            if (c1.getSelectedIndex() == 4) {
                carroceria2 = "SUV";
            }

            modelt.setValueAt(carroceria2, indice, 2);
            jTable2.setModel(modelt);
            ((David) cb.getSelectedItem()).getLista().get(indice).setCarroceria(carroceria2);

            try {
                ((David) cb.getSelectedItem()).escribirArchivo();
            } catch (IOException ex) {

            }
            JOptionPane.showMessageDialog(this, "Cambiado");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:
        DefaultTableModel modelt = (DefaultTableModel) jTable2.getModel();
        DefaultComboBoxModel modelc = (DefaultComboBoxModel) cb.getModel();
        if (jTable2.getSelectedRow() >= 0) {
            int indice = jTable2.getSelectedRow();
            jTable2.setValueAt(n1.getText(), indice, 3);
            jTable1.setModel(modelt);
            ((David) cb.getSelectedItem()).getLista().get(indice).setNumpuertas(n1.getText());

            try {
                ((David) cb.getSelectedItem()).escribirArchivo();
            } catch (IOException ex) {

            }
            JOptionPane.showMessageDialog(this, "Cambiado");
        }
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        // TODO add your handling code here:
        /*
                modificacion
        modificacion
        modificacion
        modificacion
         */

//        mostrarGeneralista.setModal(true);
//        mostrarGeneralista.pack();
//        mostrarGeneralista.setLocationRelativeTo(this);
//        mostrarGeneralista.setVisible(true);

    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        new listarAutosGeneralistas().setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        new listarAutosPremium().setVisible(true);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        new listarAutosDeportivos().setVisible(true);

    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        new BuscarVehiculo().setVisible(true);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton15MouseClicked
        // TODO add your handling code here:
        if (cb.getSelectedIndex() >= 0) {

            try {
                ((David) (cb.getSelectedItem())).escribirArchivo();
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Error");
            }

            JOptionPane.showMessageDialog(this, "El archivo se ha guardo correctamente");
        }
    }//GEN-LAST:event_jButton15MouseClicked

    private void jButton16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton16MouseClicked
        // TODO add your handling code here:
        DefaultTableModel modelt = (DefaultTableModel) jTable2.getModel();
        DefaultComboBoxModel modelc = (DefaultComboBoxModel) cb.getModel();

        Scanner sc = null;

        try {
            ((David) cb.getSelectedItem()).escribirArchivo();
        } catch (Exception e) {
        }

        JFileChooser fileChooser = new JFileChooser("./");

        int seleccion = fileChooser.showOpenDialog(this);

        if (seleccion == JFileChooser.APPROVE_OPTION) {
            //limpiar();

            try {

                File archivo = fileChooser.getSelectedFile();
                DefaultComboBoxModel modelo3 = (DefaultComboBoxModel) cb_1.getModel();

                David p = new David();
                cb_1.setModel(modelc);
                modelo3.addElement(p);
                String nombre = archivo.getName();
                int l = nombre.length();

                nombre = nombre.substring(0, l - 4);

                p.setNombre(nombre);
                modelc.setSelectedItem(p);
                sc = new Scanner(archivo);

                String file = "";

                while (sc.hasNext()) {
                    file += sc.next();

                }
                String result = file.replace("|", "/");

                sc = new Scanner(result);
                sc.useDelimiter("/");

                while (sc.hasNext()) {

                    vehiculos c = new vehiculos(sc.next(),
                            sc.next(), sc.next(),
                            sc.next(), sc.next(), sc.next(), sc.next(), sc.next(), sc.next());

                    Object[] newRow = {
                        c.getVin(),
                        c.getMarca(),
                        c.getCarroceria(),
                        c.getNumpuertas()
                    };
                    modelt.addRow(newRow);

                    p.getLista().add(c);

                }

                modelc.addElement(p);
                jTable2.setModel(modelt);
                cb.setModel(modelc);

            } catch (Exception e) {
            }
        }

    }//GEN-LAST:event_jButton16MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton c;
    private javax.swing.JComboBox<String> c1;
    private javax.swing.JTextField cantpasajeros1;
    private javax.swing.JComboBox<String> cb;
    private javax.swing.JComboBox<String> cb_1;
    private javax.swing.JComboBox<String> cbcarroceria1;
    private javax.swing.JComboBox<String> cbhibridacion1;
    private javax.swing.JComboBox<String> cbmarca1;
    private javax.swing.JComboBox<String> cbmotor1;
    private javax.swing.JTextField cnombre;
    private javax.swing.JDialog crearvehiculo;
    private javax.swing.JMenuItem delete;
    private javax.swing.JMenuItem editar;
    private javax.swing.JTextField ensamblaje1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JPopupMenu jp1;
    private javax.swing.JRadioButton m;
    private javax.swing.JTextField m1;
    private javax.swing.JComboBox<String> m11;
    private javax.swing.JTextField marca1;
    private javax.swing.JDialog modificacion;
    private javax.swing.JDialog mostrarCategoria;
    private javax.swing.JDialog mostrarGeneralista;
    private javax.swing.JTextField motor1;
    private javax.swing.JRadioButton n;
    private javax.swing.JTextField n1;
    private javax.swing.JTextField numpuertas1;
    private javax.swing.JTextField precio1;
    private javax.swing.JTextField vin1;
    // End of variables declaration//GEN-END:variables
    ArrayList<vehiculos> Creadas = new ArrayList();
}
